<?php

namespace Database\Seeders\Fake;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TreesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /***************************************************
        
            Insert Data
            
        ****************************************************/
        


        DB::table('trees')->insert([

            [
                'plant_id'           => '2B',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium australe Baby Boomer',
                'common_name'        => 'Baby Boomer Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 1.5,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '3',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium australe Captain Cook',
                'common_name'        => 'Captain Cook Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 6,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '5',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Aussie Northern',
                'common_name'        => 'Northern form Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '6',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Aussie Southern',
                'common_name'        => 'Glossy Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '7',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Wilsonii',
                'common_name'        => 'Powder Puff Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '8',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Elegance PBR',
                'common_name'        => 'Compact Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 3,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '9',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Elite',
                'common_name'        => 'Dwarf Magenta Cherry (green)',
                'mature_height_min'  => null,
                'mature_height_max'  => 3,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '10',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Elite Red',
                'common_name'        => 'Dwarf Magenta Cherry (red)',
                'mature_height_min'  => null,
                'mature_height_max'  => 3,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '11',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Express',
                'common_name'        => 'Lilly Pilly Express',
                'mature_height_min'  => null,
                'mature_height_max'  => 4,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '12',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Hinterland Gold',
                'common_name'        => 'Gold Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 4,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '13',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium Cascade PBR',
                'common_name'        => 'Cascade Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 4,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '14',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium (Waterhousea) Floribundum',
                'common_name'        => 'Weeping Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '15',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium Francisii',
                'common_name'        => "Francis's Water Gum",
                'mature_height_min'  => 8,
                'mature_height_max'  => 15,
                'mature_width_min'   => null,
                'mature_width_max'   => 6,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '16',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium (Acmena) Hemilamprum',
                'common_name'        => 'Blush Satinash Hinterland',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '17',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium australe Straight & Narrow',
                'common_name'        => 'Straight and Narrow Lilly Pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '18',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium Luehmannii',
                'common_name'        => 'Small Leaf Lilly Pilly',
                'mature_height_min'  => 8,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '19',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium (Acmena) Smithii Firescreen',
                'common_name'        => 'Lilly Pilly Firescreen',
                'mature_height_min'  => null,
                'mature_height_max'  => 6,
                'mature_width_min'   => null,
                'mature_width_max'   => 2.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '20',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium a. Purple Rain',
                'common_name'        => 'Lilly Pilly Purple Rain',
                'mature_height_min'  => 3,
                'mature_height_max'  => 4,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '21',
                'tree_type_id'       => 1,
                'botanical_name'     => 'Syzygium Resilience',
                'common_name'        => 'Psyllid resistant lilly pilly',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 2.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '22',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Agathis Robusta',
                'common_name'        => 'Queensland Kauri Pine',
                'mature_height_min'  => null,
                'mature_height_max'  => 45,
                'mature_width_min'   => null,
                'mature_width_max'   => 8,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '23',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Backhousia Citriodora',
                'common_name'        => 'Lemon Scented Myrtle',
                'mature_height_min'  => null,
                'mature_height_max'  => 6,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '24',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Brachychiton Acerifolius',
                'common_name'        => 'Illawarra Flame Tree',
                'mature_height_min'  => null,
                'mature_height_max'  => 12,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '25',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Brachychiton Rupestris',
                'common_name'        => 'Queensland Bottle Tree',
                'mature_height_min'  => null,
                'mature_height_max'  => 20,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '26',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Buckinghamia Celsissima',
                'common_name'        => 'Ivory-curl Tree',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '27',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Cupaniopsis Anacardioides',
                'common_name'        => 'Tuckeroo',
                'mature_height_min'  => null,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '28',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Elaeocarpus Eumundii',
                'common_name'        => 'Eumundi Quondong',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '29',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Elaeocarpus Reticulatus',
                'common_name'        => 'Blueberry Ash',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '32',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Ficus Microcarpa Hillii',
                'common_name'        => 'Hills Fig',
                'mature_height_min'  => null,
                'mature_height_max'  => 15,
                'mature_width_min'   => null,
                'mature_width_max'   => 10,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '34',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Tristaniopsis Laurina Luscious',
                'common_name'        => 'Water Gum',
                'mature_height_min'  => 7,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '35',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Grevillea cv. Honey Gem',
                'common_name'        => 'Orange Grevillia',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '36',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Grevillea cv. Moonlight',
                'common_name'        => 'White Grevillea',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '37',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Harpullia Pendula',
                'common_name'        => 'Tulipwood',
                'mature_height_min'  => 8,
                'mature_height_max'  => 10,
                'mature_width_min'   => 4,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '38',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Hibiscus Tiliaceus Rubra',
                'common_name'        => 'Bronze Cottonwood',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 6,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '39',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Lophostemon Confertus',
                'common_name'        => 'Brush Box',
                'mature_height_min'  => null,
                'mature_height_max'  => 15,
                'mature_width_min'   => null,
                'mature_width_max'   => 8,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '40',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Melaleuca Leucadendra Broad Leaf',
                'common_name'        => 'Broad Leaf Paperbark',
                'mature_height_min'  => null,
                'mature_height_max'  => 12,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '41',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Melaleuca Leucadendra Fine Leaf',
                'common_name'        => 'Fine Leaf Paperbark',
                'mature_height_min'  => 10,
                'mature_height_max'  => 12,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '42',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Callistemon Viminalis Wilderness Red',
                'common_name'        => 'Wilderness Red Bottlebrush',
                'mature_height_min'  => 3,
                'mature_height_max'  => 4,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '43',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Melaleuca (Callistemon) cv. Taree Pink',
                'common_name'        => 'Pink Bottlebrush',
                'mature_height_min'  => null,
                'mature_height_max'  => 3,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '45',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Melicope Rubra Blush',
                'common_name'        => 'Little Evodia',
                'mature_height_min'  => null,
                'mature_height_max'  => 6,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '46',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Randia Fitzalanii',
                'common_name'        => 'Native Gardenia',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '47',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Xanthostemon Chrysanthus',
                'common_name'        => 'Golden Penda',
                'mature_height_min'  => null,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '47LG',
                'tree_type_id'       => 2,
                'botanical_name'     => 'Xanthostemon Chrysanthus Little Goldie',
                'common_name'        => 'Little Goldie',
                'mature_height_min'  => 2,
                'mature_height_max'  => 4,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '48',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Brunsfelsia Latifolia',
                'common_name'        => 'Yesterday, Today, Tomorrow',
                'mature_height_min'  => null,
                'mature_height_max'  => 2,
                'mature_width_min'   => null,
                'mature_width_max'   => 1,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '49',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Caesalpinia Ferrea',
                'common_name'        => 'Leopard Tree',
                'mature_height_min'  => null,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '50',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Delonix Regia',
                'common_name'        => 'Poinciana',
                'mature_height_min'  => null,
                'mature_height_max'  => 12,
                'mature_width_min'   => null,
                'mature_width_max'   => 10,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '53',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Jacaranda Mimosifolia',
                'common_name'        => 'Jacaranda',
                'mature_height_min'  => null,
                'mature_height_max'  => 12,
                'mature_width_min'   => null,
                'mature_width_max'   => 8,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '54',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Lagerstroemia Enduring Summer Red',
                'common_name'        => 'Red Crepe Myrtle',
                'mature_height_min'  => null,
                'mature_height_max'  => 1.5,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '55',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Magnolia Grandiflora Teddy Bear',
                'common_name'        => 'Magnolia grandiflora Teddy Bear',
                'mature_height_min'  => 4,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '56',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Magnolia Grandiflora Exmouth',
                'common_name'        => 'Magnolia Exmouth',
                'mature_height_min'  => null,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '57',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Magnolia Grandiflora Little Gem',
                'common_name'        => 'Magnolia Little Gem',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '58',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Metrosideros vit Fiji Fire',
                'common_name'        => 'Fiji Christmas Bush',
                'mature_height_min'  => null,
                'mature_height_max'  => 3,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '59',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Metrosideros cv. Thomasii',
                'common_name'        => 'New Zealand Christmas Bush',
                'mature_height_min'  => null,
                'mature_height_max'  => 4,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '60',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Michelia Figo Coco',
                'common_name'        => 'Large Leafed Port Wine Magnolia',
                'mature_height_min'  => null,
                'mature_height_max'  => 2.5,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '61',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Michelia Figo',
                'common_name'        => 'Port Wine Magnolia',
                'mature_height_min'  => null,
                'mature_height_max'  => 2,
                'mature_width_min'   => null,
                'mature_width_max'   => 1.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '62',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Murraya Paniculata',
                'common_name'        => 'Mock Orange',
                'mature_height_min'  => null,
                'mature_height_max'  => 3,
                'mature_width_min'   => null,
                'mature_width_max'   => 2,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '67',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Tabebuia Pallida',
                'common_name'        => 'Pale Pink Trumpet Tree',
                'mature_height_min'  => null,
                'mature_height_max'  => 6,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '68',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Tabebuia Palmeri',
                'common_name'        => 'Pink Trumpet Tree',
                'mature_height_min'  => null,
                'mature_height_max'  => 8,
                'mature_width_min'   => null,
                'mature_width_max'   => 5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '69',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Tibouchina Lepidota Alstonville',
                'common_name'        => 'Lasiandra',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '78',
                'tree_type_id'       => 3,
                'botanical_name'     => 'Olea Europaea Heritage Frantoia',
                'common_name'        => 'Olive Tree',
                'mature_height_min'  => null,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '70',
                'tree_type_id'       => 4,
                'botanical_name'     => 'Archontophoenix Alexandrae',
                'common_name'        => 'Alexandra Palm',
                'mature_height_min'  => null,
                'mature_height_max'  => 20,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '70B',
                'tree_type_id'       => 4,
                'botanical_name'     => 'Archontophoenix Alexandrae Beautrice',
                'common_name'        => 'Alexandra Palm Beautrice',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '71',
                'tree_type_id'       => 4,
                'botanical_name'     => 'Archontophoenix Cunninghamiana',
                'common_name'        => 'Bangalow Palm',
                'mature_height_min'  => null,
                'mature_height_max'  => 20,
                'mature_width_min'   => null,
                'mature_width_max'   => 4,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '72',
                'tree_type_id'       => 4,
                'botanical_name'     => 'Bismarckia Nobilis',
                'common_name'        => 'Bismark Palm',
                'mature_height_min'  => null,
                'mature_height_max'  => 10,
                'mature_width_min'   => null,
                'mature_width_max'   => 10,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '73',
                'tree_type_id'       => 4,
                'botanical_name'     => 'Dypsis Lutescens',
                'common_name'        => 'Golden Cane Palm',
                'mature_height_min'  => null,
                'mature_height_max'  => 5,
                'mature_width_min'   => null,
                'mature_width_max'   => 2.5,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

            [
                'plant_id'           => '76',
                'tree_type_id'       => 4,
                'botanical_name'     => 'Wodyetia Bifurcata',
                'common_name'        => 'Foxtail Palm',
                'mature_height_min'  => null,
                'mature_height_max'  => 15,
                'mature_width_min'   => null,
                'mature_width_max'   => 3,
                'created_by'         => null,
                'modified_by'        => null,
                'created_at'         => now(),
                'updated_at'         => now(),
            ],

        ]);
        
    }
}
